### ISSUE TITLE
Does it work on django 1.10

### ISSUE THREAD

**Issue by sosico** [ramusus/django-instagram-api#10]
Hi! I'm getting an error trying to install this,  it is an error related with m2mhistory 
/lib/python2.7/site-packages/m2m_history/fields.py", line 3, in <module>
    from .descriptors import ManyRelatedObjectsHistoryDescriptor, ReverseManyRelatedObjectsHistoryDescriptor
  File "/lib/python2.7/site-packages/m2m_history/descriptors.py", line 7, in <module>
    from django.db.models.fields.related import ManyRelatedObjectsDescriptor, ReverseManyRelatedObjectsDescriptor, \
**ImportError: cannot import name ManyRelatedObjectsDescriptor**

m2m-history is not compatible with django 1.9 - 1.10

**Comment by martinszy** [comment]
Yes, I run into the same problem, so I added django==1.8 to my requirements.txt to get it to run, but I run into other issues.
